name: PHP Tests
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: phar
          tools: composer:v2
          coverage: xdebug
          ini-values: phar.readonly=0

      - name: Install PHPUnit
        run: |
          composer require --dev phpunit/phpunit
          composer dump-autoload

      - name: Create temp directories
        run: |
          mkdir -p temp_install/packages
          mkdir -p temp_install/app/commands
          mkdir -p temp_install/app/controllers
          mkdir -p temp_install/app/rules
          mkdir -p temp_install/routes
          mkdir -p temp_install/storage/downloads
          mkdir -p temp_install/storage/documentation
          chmod -R 755 temp_install

      - name: Build PHAR for testing
        run: |
          php dev_build.php
          # Verify the PHAR exists and is readable
          test -f temp_install/packages/lucent.phar || (echo "PHAR not created" && exit 1)

      - name: Run tests
        run: |
          # Set working directory to ensure correct paths
          cd ${{ github.workspace }}
          ./vendor/bin/phpunit --configuration phpunit.xml
        env:
          TEMP_ROOT: ${{ github.workspace }}/temp_install/

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            phpunit.log
            temp_install/
